### ISSUE TITLE
Execute all data migrations at once

### ISSUE THREAD

**Issue by zarunet** [fndmiranda/data-migration#1]
I started using this package for a customer project, and noticed that the only option to execute data migration was to do them one at a time, giving the classname as a parameter.

Could a way to execute all data migrations at once (*à la* `artisan migrate`) be added? (if yes, i may be able to provide a PR for it)

**Comment by fndmiranda** [comment]
> I started using this package for a customer project, and noticed that the only option to execute data migration was to do them one at a time, giving the classname as a parameter.
> 
> Could a way to execute all data migrations at once (_à la_ `artisan migrate`) be added? (if yes, i may be able to provide a PR for it)

Hello @zarunet, really still do not have a way to run all at once, can send the PR, your contribution will be very welcome.

**Comment by fndmiranda** [comment]
@zarunet I made some changes to your PR and I already did the merge, please check and thank you for using the package and for your collaboration with the PR.

**Comment by zarunet** [comment]
Well, you basically nuked all my changes, but hey, the feature is still here, so who cares? :>  
Also, kudos for extending it to the other commands !
